### PR TITLE
fix fatal error + add select2 to all selects

### PR DESCRIPTION
**Pull request by jmau111**
there is a fatal error with ```do_action( 'wp_login', $user_data->user_login);```, there is a second argument needed which is the whole user object.

if more than 20 users it become a little bit tedious

### CODE REVIEW

**Comment by BoiteAWeb** [comment]
too much modifications + I dont like to link a distant JS
next time, 1 modification = 1 PR ;) thanks
I'll still patch the login issue

**Comment by jmau111** [comment]
too bad for you. tchao

**Comment by jmau111** [comment]
for real, this simple select with 200 users is not usable, kinda disappointed you did not approve but I respect that choice so I made my own version that's the spirit :) #fork

**Comment by jmau111** [comment]
that solution is perfect, if no js then current select, do not understand the distant js issue

**Comment by BoiteAWeb** [comment]
it's not secure to load scripts from external resource, it's always a risk. this is why I prefer to load jquery from WP core and not from distant website (in 2014, jquery.com was victim of a hack, why not CF tomorrow?)
I would ratherly prefer to embed those scripts directly in the backdoor file.

**Comment by jmau111** [comment]
but the very concept of this tool is too be temporary and renamed so I don t see how this could be infected by some hypothetical xss or anything else.

**Comment by BoiteAWeb** [comment]
"tomorrow" the external ressource is hacked, I'm a user, not aware of this flaw. I use this script on my website, pwed.
Yep, I'm paranoid, that's my job to be :)

**Comment by jmau111** [comment]
You 're probably right but at the end of the day I think the probability is very very low. But I understand the "in case" thing :)

**Comment by BoiteAWeb** [comment]
Yep, the thing is "it happened for jquery.com in 2014", so I don't want my script to be a cause of hacked websites :O
I rather prefer to include the whole file contents in my script.
Sounds good for me. You?

**Comment by jmau111** [comment]
Yes, understand the whole thing but it's in the current version of your tool that I found this :
`https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css`

so that's the reason why I did not understand the first time "distant resources"

**Pull request closed without merging**
